### ISSUE TITLE
Organizzare le pagine per edizione del Linux Day

### ISSUE THREAD

**Issue by andros1963** [Openlabs-aps/linuxdaymilano.org#2]
L'edizione 2016 è sul dominio principale, mentre è preferibile che ogni edizione abbia la sua pagina **/aaaa**, e che il dominio principale punti all'edizione in corso.
Il tal modo avremo:
- **linuxdaymilano.org/aaaa+1** per l'anno successivo (template e successivo work in progress)
- linuxdaymilano.org --> **linuxdaymilano.org/aaaa** per l'edizione in corso di allestimento
- **linuxdaymilano.org/aaaa-n** per le edizioni precedenti

Per il 2015 reindirizzare alla [vecchia pagina sul sito OpenLabs](http://www.openlabs.it/attivita/linux-day-2015). In seguito valuteremo se inserire i contenuti del 2015 in una apposita pagina col template corrente.

Per il 2017 copiare la pagina 2016 (quando sarà conclusa), e sostituire i contenuti con placeholders tipo _lorem ipsum_.

**Comment by Sjd-Risca** [comment]
Concordo con l'idea, sulla root si dovrebbe impostare qualcosa del genere:

```
<html>
  <head>
    <title>Pagina di Redirect</title>
    <meta http-equiv="refresh" content="15;URL=http://www.linuxdaymilano.org/2016.html">
  </head>
  <body>
    <p>
    Tra 15 secondi avverrà un redirect automatico alla pagina dedicata al linuxday di quest'anno.<br>
    Se non vuoi aspettare <a href="http://www.linuxdaymilano.org/2016.html">clicca qui</a>.
    </p>
  </body>
</html>
```

Per riorganizzare la home è necessario però riorganizzare tutti i link, non so a livello di javascript e css se possano esserci difficoltà.

**Comment by Sjd-Risca** [comment]
Chiuso con commit 86c875f642a7ada7f8f8cb134b8a8163ca24b0c1
